export const ASSETS = {
  backgrounds: {
    start: '/assets/backgrounds/bg-Inicio.png',
    pet: '/assets/backgrounds/bg-pet2.png',
    footballField: '/assets/backgrounds/bg-football-field.png',
    footballResults: '/assets/backgrounds/bg-football-results.png',
    qr: '/assets/backgrounds/QR.png',
  },
  ui: {
    logo: '/assets/ui/logo-nutre-cat.svg',
    handPointer: '/assets/ui/hand-pointer.svg',
    clock: '/assets/ui/icon-clock.svg',
  },
  nav: {
    game: '/assets/nav/icon-game.svg',
    food: '/assets/nav/icon-food.svg',
    sleep: '/assets/nav/icon-sleep.svg',
  },
  products: {
    treats: '/assets/products/product-1.png',
    wet: '/assets/products/product-2.png',
    dry: '/assets/products/product-3.png',
  },
  reward: {
    background: '/assets/reward/final-bg.png',
    cat: '/assets/reward/final-cat.png',
    star: '/assets/reward/final-star.svg',
  },
  benefitIcons: {
    digestive: '/assets/icons/benefit-digestive.svg',
    bone: '/assets/icons/benefit-bone.svg',
    tilapiaDigestive: '/assets/icons/benefit-digestive-tilapia.svg',
    salmon1: '/assets/cat/Salmon1.png?v=salmon-popup-1',
    salmon2: '/assets/cat/Salmon2.png?v=salmon-popup-1',
    tilapia2: '/assets/cat/Tilapila2.png',
  },
  cat: {
    foodLightBackground: '/assets/cat/Fondo%20con%20luz%201.png',
    catchPaw: '/assets/cat/PaticaAtrapalo.png',
  },
  catVideos: {
    attractBox: '/assets/cat/Animation/caja.webm',
    idle: '/assets/cat/Animation/Esperando.webm',
    idle2: '/assets/cat/Animation/Esperando2.webm',
    idle3: '/assets/cat/Animation/Esperando3.webm',
    petting: '/assets/cat/Animation/Concentir.webm',
    celebrate: '/assets/cat/Animation/Celebrando.webm',
    defeat: '/assets/cat/Animation/Perdedor.webm',
    foodIdle: '/assets/cat/Animation/EsperandoComida.webm',
    eating: '/assets/cat/Animation/Comiendo.webm',
    foodExit: '/assets/cat/Animation/SalidaComida.webm',
    sleepy: '/assets/cat/Animation/CasiDormido.webm',
    sleeping: '/assets/cat/Animation/Dormido.webm',
    playerBack: '/assets/cat/Animation/EspaldasNaranja.webm',
    playerKick: '/assets/cat/Animation/JugadorPrincipalGolpeobalon.webm',
    rivalIdle: '/assets/cat/Animation/RivalIdle.webm',
    rivalKick: '/assets/cat/Animation/RivalGolpeo.webm',
    rivalKeeperIdle: '/assets/cat/Animation/ArqueroRivalIdle.webm',
    rivalKeeperLeft: '/assets/cat/Animation/ArqueroRivalIzquierda.webm',
    rivalKeeperRight: '/assets/cat/Animation/ArqueroRivalDerecha.webm',
    rivalKeeperCenter: '/assets/cat/Animation/ArqueroRivalCentro.webm',
    playerKeeperIdle: '/assets/cat/Animation/ArqueroPrincipalIdle.webm',
    playerKeeperJumpCenter: '/assets/cat/Animation/ArqueroPrincipalSaltoCentro.webm',
  },
  games: {
    selectionBall: '/assets/games/ball.svg',
    footballBall: '/assets/games/football-ball.svg',
    bagTop: '/assets/games/bag-top.svg',
    bagLeft: '/assets/games/bag-left.svg',
    bagRight: '/assets/games/bag-right.svg',
    mouse: '/assets/games/mouse_no_bg.png',
    fishbone: '/assets/games/fishbone_no_bg.png',
    instruction1: '/assets/games/FG-Instruction1.png',
    instruction2: '/assets/games/FG-Instruction2.png',
    instruction3: '/assets/games/FG-Instruction3.png',
    instruction4: '/assets/games/FG-Instruction4.png',
  },
  catchInstructions: {
    deadCreature: '/assets/instructions/bags-dead-creature.png',
    mouse: '/assets/instructions/bags-mouse.png',
  },
} as const;

export const catVideoByName = (name: string) => `/assets/cat/Animation/${name}.webm`;
export const cssUrl = (asset: string) => `url(${asset})`;
